name: petsitter
description: "Pet sitter app"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  # Add required dependencies for the app
  cupertino_icons: ^1.0.6
  http: ^1.2.2  # Updated http version
  shared_preferences: ^2.0.13
  image_picker: ^1.1.2  # Update to the latest version
  permission_handler: ^11.3.1  # Update to the latest version
  path_provider: ^2.0.11    # Helps in managing file paths
  flutter_image_compress: ^2.3.0  # Update to the latest version
  uuid: ^4.5.1   # For generating unique IDs
  video_player: ^2.2.17
  share_plus: ^10.0.2
  url_launcher: ^6.3.0
  intl: ^0.19.0
  elegant_notification: ^2.3.0







dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0  # Update to the latest version

flutter:
  uses-material-design: true

  # You can uncomment and use this for any custom assets you may have
  assets:
      - assets/hola.mp4
      - assets/logo.png
      - assets/blueman.png
      - assets/hello.png
      - assets/cover.jpg
      - assets/pic1.jpg
      - assets/pic2.jpg
      - assets/pic3.jpg
      - assets/cancel.png
      - assets/pending.png
      - assets/mark.png

  #   - images/a_dot_ham.jpeg

  # For adding fonts or any other custom settings, you can customize here.
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
